; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?qt_meta_stringdata_SourceMaker@@3Uqt_meta_stringdata_SourceMaker_t@@B DD 0ffffffffH ; qt_meta_stringdata_SourceMaker
	DD	0bH
	DD	00H
	ORG $+4
	DQ	00000000000000a8H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	000000000000009cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000096H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	000000000000007fH
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000071H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000066H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	000000000000005aH
	DB	'SourceMaker', 00H, 'onSavePathChanged', 00H, 00H, 'onPre'
	DB	'ssed', 00H, 'onMulPressed', 00H, 'onUnPressed', 00H, 'onCodeC'
	DB	'hanged', 00H
	ORG $+8
?qt_meta_data_SourceMaker@@3QBIB DD 07H			; qt_meta_data_SourceMaker
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	027H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	028H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	029H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	02aH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	02bH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG134260 DB	'D:\Software\Qt\5.9.2\msvc2015_64\include\QtCore/qmetatyp'
	DB	'e.h', 00H
	ORG $+12
$SG134261 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG134262 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136399 DB	'D:\Software\Qt\5.9.2\msvc2015_64\include\QtCore/qmetatyp'
	DB	'e.h', 00H
	ORG $+4
$SG136400 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136401 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG137460 DB	'D:\Software\Qt\5.9.2\msvc2015_64\include\QtCore/qmetatyp'
	DB	'e.h', 00H
	ORG $+4
$SG137461 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG137462 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG134562 DB	'D:\Software\Qt\5.9.2\msvc2015_64\include\QtCore/qmetatyp'
	DB	'e.h', 00H
	ORG $+4
$SG134563 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG134564 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136701 DB	'D:\Software\Qt\5.9.2\msvc2015_64\include\QtCore/qmetatyp'
	DB	'e.h', 00H
	ORG $+4
$SG136702 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136703 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG135753 DB	'D:\Software\Qt\5.9.2\msvc2015_64\include\QtCore/qmetatyp'
	DB	'e.h', 00H
	ORG $+4
$SG135754 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG135755 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG134864 DB	'D:\Software\Qt\5.9.2\msvc2015_64\include\QtCore/qmetatyp'
	DB	'e.h', 00H
	ORG $+4
$SG134865 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG134866 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG136097 DB	'D:\Software\Qt\5.9.2\msvc2015_64\include\QtCore/qmetatyp'
	DB	'e.h', 00H
	ORG $+4
$SG136098 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG136099 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@SourceMaker@@UEBAPEBUQMetaObject@@XZ ; SourceMaker::metaObject
PUBLIC	?qt_metacast@SourceMaker@@UEAAPEAXPEBD@Z	; SourceMaker::qt_metacast
PUBLIC	?qt_metacall@SourceMaker@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; SourceMaker::qt_metacall
PUBLIC	?qt_static_metacall@SourceMaker@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; SourceMaker::qt_static_metacall
PUBLIC	?staticMetaObject@SourceMaker@@2UQMetaObject@@B	; SourceMaker::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onSavePathChanged@SourceMaker@@AEAAXXZ:PROC	; SourceMaker::onSavePathChanged
EXTRN	?onPressed@SourceMaker@@AEAAXXZ:PROC		; SourceMaker::onPressed
EXTRN	?onMulPressed@SourceMaker@@AEAAXXZ:PROC		; SourceMaker::onMulPressed
EXTRN	?onUnPressed@SourceMaker@@AEAAXXZ:PROC		; SourceMaker::onUnPressed
EXTRN	?onCodeChanged@SourceMaker@@AEAAXXZ:PROC	; SourceMaker::onCodeChanged
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@SourceMaker@@2UQMetaObject@@B DB 030H DUP (?) ; SourceMaker::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@SourceMaker@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@SourceMaker@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@SourceMaker@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@SourceMaker@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@SourceMaker@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@SourceMaker@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@SourceMaker@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN12
	DD	imagerel $LN12+148
	DD	imagerel $unwind$?qt_static_metacall@SourceMaker@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@SourceMaker@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@SourceMaker@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@SourceMaker@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@SourceMaker@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@SourceMaker@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@SourceMaker@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@SourceMaker@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@SourceMaker@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@SourceMaker@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'SourceMaker::staticMetaObject'', COMDAT
; File e:\mygit\quazipprj\sourcemaker\generatedfiles\debug\moc_sourcemaker.cpp
; Line 96
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@SourceMaker@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_SourceMaker@@3Uqt_meta_stringdata_SourceMaker_t@@B
	mov	QWORD PTR ?staticMetaObject@SourceMaker@@2UQMetaObject@@B+8, rax
; Line 97
	lea	rax, OFFSET FLAT:?qt_meta_data_SourceMaker@@3QBIB
	mov	QWORD PTR ?staticMetaObject@SourceMaker@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@SourceMaker@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; SourceMaker::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@SourceMaker@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@SourceMaker@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@SourceMaker@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@SourceMaker@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'SourceMaker::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@SourceMaker@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; SourceMaker::qt_static_metacall
; File e:\mygit\quazipprj\sourcemaker\generatedfiles\debug\moc_sourcemaker.cpp
; Line 79
$LN12:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 80
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 81
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 83
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	SHORT $LN8@qt_static_
	cmp	DWORD PTR tv69[rsp], 4
	je	SHORT $LN9@qt_static_
	jmp	SHORT $LN10@qt_static_
$LN5@qt_static_:
; Line 84
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onSavePathChanged@SourceMaker@@AEAAXXZ	; SourceMaker::onSavePathChanged
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 85
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onPressed@SourceMaker@@AEAAXXZ		; SourceMaker::onPressed
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 86
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onMulPressed@SourceMaker@@AEAAXXZ	; SourceMaker::onMulPressed
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 87
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onUnPressed@SourceMaker@@AEAAXXZ	; SourceMaker::onUnPressed
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 88
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onCodeChanged@SourceMaker@@AEAAXXZ	; SourceMaker::onCodeChanged
$LN10@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 93
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@SourceMaker@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; SourceMaker::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@SourceMaker@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; SourceMaker::qt_metacall
; File e:\mygit\quazipprj\sourcemaker\generatedfiles\debug\moc_sourcemaker.cpp
; Line 115
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 116
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 117
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 119
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 120
	cmp	DWORD PTR _id$[rsp], 5
	jge	SHORT $LN5@qt_metacal
; Line 121
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@SourceMaker@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; SourceMaker::qt_static_metacall
$LN5@qt_metacal:
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 5
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 123
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 124
	cmp	DWORD PTR _id$[rsp], 5
	jge	SHORT $LN7@qt_metacal
; Line 125
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 126
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 5
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 128
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 129
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@SourceMaker@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; SourceMaker::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@SourceMaker@@UEAAPEAXPEBD@Z PROC		; SourceMaker::qt_metacast
; File e:\mygit\quazipprj\sourcemaker\generatedfiles\debug\moc_sourcemaker.cpp
; Line 107
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 108
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 109
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_SourceMaker@@3Uqt_meta_stringdata_SourceMaker_t@@B+168
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 110
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 111
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 112
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@SourceMaker@@UEAAPEAXPEBD@Z ENDP		; SourceMaker::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@SourceMaker@@UEBAPEBUQMetaObject@@XZ PROC	; SourceMaker::metaObject
; File e:\mygit\quazipprj\sourcemaker\generatedfiles\debug\moc_sourcemaker.cpp
; Line 102
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 103
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@SourceMaker@@2UQMetaObject@@B ; SourceMaker::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 104
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@SourceMaker@@UEBAPEBUQMetaObject@@XZ ENDP	; SourceMaker::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\software\qt\5.9.2\msvc2015_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File e:\mygit\quazipprj\sourcemaker\generatedfiles\debug\moc_sourcemaker.cpp
; Line 132
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File e:\mygit\quazipprj\sourcemaker\generatedfiles\debug\moc_sourcemaker.cpp
; Line 132
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
